package provider

func init() {
	additionalBrowserProcessEnvironmentKeys = []string{
		"PRODUCT_CAPTURE_TEST_BINARY",
		"PRODUCT_CAPTURE_TEST_BLOCK_CLEANUP_COMMAND",
		"PRODUCT_CAPTURE_TEST_CHROME_BINARY",
		"PRODUCT_CAPTURE_TEST_CONNECT_DELAY_MS",
		"PRODUCT_CAPTURE_TEST_CRASH_ON_VERSION_ONCE",
		"PRODUCT_CAPTURE_TEST_DIAGNOSTIC_JSON_PATH",
		"PRODUCT_CAPTURE_TEST_DISPLAY_FILE",
		"PRODUCT_CAPTURE_TEST_EXPECT_PROFILE_DIR",
		"PRODUCT_CAPTURE_TEST_MKTEMP_COUNT",
		"PRODUCT_CAPTURE_TEST_NATIVE_CHROME",
		"PRODUCT_CAPTURE_TEST_PERSIST_SESSION_STATE",
		"PRODUCT_CAPTURE_TEST_PROFILE_DIR",
		"PRODUCT_CAPTURE_TEST_PROFILE_MARKER",
		"PRODUCT_CAPTURE_TEST_RELEASE",
		"PRODUCT_CAPTURE_TEST_STARTED",
		"PRODUCT_CAPTURE_TEST_TEMP_DIR",
		"PRODUCT_CAPTURE_TEST_XVFB_PID_PATH",
	}
}
